### ISSUE TITLE
404 error when going to play.astro.build

### ISSUE THREAD

**Issue by 4lch4** [snowpackjs/play.astro.build#1]
I know I'm not the most active so I may have missed something, but I was poking around and noticed going to https://play.astro.build/ gives me a 404: NOT_FOUND error:

```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: cle1::2tjrt-1630717807343-6390f851331e

play.astro.build might be available. Click here to learn how to assign it to a project.
```

I'd post a screenshot but my PC is acting up at the moment so copy/paste is the best I can do for now :(

**Comment by jasikpark** [comment]
Don't believe there's a project that actually exists at that location yet 😅 I'm extremely excited to see that happen once `#compiler-v2` drops!

**Comment by 4lch4** [comment]
> Don't believe it's meant to be live yet 😅 I'm extremely excited to see that happen once `#compiler-v2` drops!

Well, that explains it 😂 Thanks, @jasikpark!
